version: '3.8'

services:
  db:
    image: postgres:17
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5434:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
